name = "26 che modda"
author = "26 che gioca"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a06869b8cf580a79f00d02faf4eb463ffc559e4b28a71d929bf51b85f6b2bae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
