name = "26 che modda"
author = "26 che gioca"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ee7e63db99be34c53ae401117d64a145b74fb68563c2e03bf823e80645dffe9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
