name = "26 che modda"
author = "26 che gioca"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e12c4dcf51b9c1c6a7633350492e8d1cd0d765943887afa31bba94e05cffbd3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
