name = "26 che modda"
author = "26 che gioca"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4d94a0c6c44e35597d716ededce0de34101dc62b851f02eeec1171fef0cdbaf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
